<?php

namespace Plugin\ProductLimit\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductLimitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLimitRepository extends EntityRepository
{
}
